services:
  - type: web
    name: notas
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -w 2 -b 0.0.0.0:$PORT
    autoDeploy: true
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: SECRET_KEY
        value: change-me
      - key: DATABASE
        value: /var/data/app.db
